// console.log("Hello World")
// declaring a variable
// var let const

//let nam = "Paul" 
// var age = 80;
// const school = "GoMycode"
// const address = "yaba, Lagos"

// console.log( name, school, address);

//Data Types
// boolean string number undefined null symbol

const age = 100 // number
const isMale = true//boolean
const nam = "Elfreda" // string
let z                  //undefined
let x = null           //null
console.log(nam, age, isMale, z, x)